# Uncomment the next line to define a global platform for your project
 platform :ios, '11.3'

target 'GlassShoes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'		
  # Pods for GlassShoes

  target 'GlassShoesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlassShoesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
